export const comboBoxOptions = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina"
];

export const comboBoxObjectOptions = [
  { id: "0", country: "Afghanistan" },
  { id: "1", country: "Aland Islands" },
  { id: "2", country: "Albania" },
  { id: "3", country: "Algeria" },
  { id: "4", country: "American Samoa" },
  { id: "5", country: "Andorra" },
  { id: "6", country: "Angola" },
  { id: "7", country: "Anguilla" },
  { id: "8", country: "Antarctica" },
  { id: "9", country: "Antigua and Barbuda" },
  { id: "10", country: "Argentina" },
  { id: "11", country: "Australia" },
  { id: "12", country: "Austrian Empire" },
  { id: "13", country: "Austria" },
  { id: "14", country: "Azerbaijan" },
  { id: "15", country: "Bahrain" },
  { id: "16", country: "Bangladesh" },
  { id: "17", country: "Barbados" },
  { id: "18", country: "Bavaria" },
  { id: "19", country: "Belarus" },
  { id: "20", country: "Belgium" },
  { id: "21", country: "Belize" },
  { id: "22", country: "Cabo Verde" },
  { id: "23", country: "Cambodia" },
  { id: "24", country: "Cameroon" },
  { id: "25", country: "Canada" },
  { id: "26", country: "Cayman Islands" },
  { id: "27", country: "The Central African Republic" },
  { id: "28", country: "Chad" }
];

export const comboBoxComplexObjectOption = [
  {
    countryNameEn: "Andorra",
    countryNameLocal: "Andorra",
    countryCode: "AD",
    currencyCode: "EUR",
    currencyNameEn: "Euro",
    tinType: "",
    tinName: "",
    officialLanguageCode: "ca",
    officialLanguageNameEn: "Catalan, Valencian",
    officialLanguageNameLocal: "Català, Valencià",
    countryCallingCode: "376",
    region: "Europe",
    flag: "🇦🇩"
  },
  {
    countryNameEn: "Afghanistan",
    countryNameLocal: "د افغانستان اسلامي دولتدولت اسلامی افغانستان, جمهوری اسلامی افغانستان",
    countryCode: "AF",
    currencyCode: "AFN",
    currencyNameEn: "Afghan afghani",
    tinType: "",
    tinName: "",
    officialLanguageCode: "fa",
    officialLanguageNameEn: "Persian",
    officialLanguageNameLocal: "فارسی",
    countryCallingCode: "93",
    region: "Asia & Pacific",
    flag: "🇦🇫"
  },
  {
    countryNameEn: "Antigua and Barbuda",
    countryNameLocal: "Antigua and Barbuda",
    countryCode: "AG",
    currencyCode: "XCD",
    currencyNameEn: "East Caribbean dollar",
    tinType: "",
    tinName: "",
    officialLanguageCode: "en",
    officialLanguageNameEn: "English",
    officialLanguageNameLocal: "English",
    countryCallingCode: "1268",
    region: "South/Latin America",
    flag: "🇦🇬"
  },
  {
    countryNameEn: "Anguilla",
    countryNameLocal: "Anguilla",
    countryCode: "AI",
    currencyCode: "XCD",
    currencyNameEn: "East Caribbean dollar",
    tinType: "",
    tinName: "",
    officialLanguageCode: "en",
    officialLanguageNameEn: "English",
    officialLanguageNameLocal: "English",
    countryCallingCode: "1264",
    region: "South/Latin America",
    flag: "🇦🇮"
  },
  {
    countryNameEn: "Albania",
    countryNameLocal: "Shqipëria",
    countryCode: "AL",
    currencyCode: "ALL",
    currencyNameEn: "Albanian lek",
    tinType: "NIPT",
    tinName: "Numri i Identifikimit për Personin e Tatueshëm",
    officialLanguageCode: "sq",
    officialLanguageNameEn: "Albanian",
    officialLanguageNameLocal: "Shqip",
    countryCallingCode: "355",
    region: "Europe",
    flag: "🇦🇱"
  },
  {
    countryNameEn: "Armenia",
    countryNameLocal: "Հայաստան",
    countryCode: "AM",
    currencyCode: "AMD",
    currencyNameEn: "Armenian dram",
    tinType: "",
    tinName: "",
    officialLanguageCode: "hy",
    officialLanguageNameEn: "Armenian",
    officialLanguageNameLocal: "Հայերեն",
    countryCallingCode: "374",
    region: "Europe",
    flag: "🇦🇲"
  },
  {
    countryNameEn: "Angola",
    countryNameLocal: "Angola",
    countryCode: "AO",
    currencyCode: "AOA",
    currencyNameEn: "Angolan kwanza",
    tinType: "",
    tinName: "",
    officialLanguageCode: "pt",
    officialLanguageNameEn: "Portuguese",
    officialLanguageNameLocal: "Português",
    countryCallingCode: "244",
    region: "Africa",
    flag: "🇦🇴"
  },
  {
    countryNameEn: "Antarctica",
    countryNameLocal: "Antarctica, Antártico, Antarctique, Антарктике",
    countryCode: "AQ",
    currencyCode: "",
    currencyNameEn: "",
    tinType: "",
    tinName: "",
    officialLanguageCode: "en",
    officialLanguageNameEn: "English",
    officialLanguageNameLocal: "English",
    countryCallingCode: "672",
    region: "Asia & Pacific",
    flag: "🇦🇶"
  },
  {
    countryNameEn: "Argentina",
    countryNameLocal: "Argentina",
    countryCode: "AR",
    currencyCode: "ARS",
    currencyNameEn: "Argentine peso",
    tinType: "CUIT",
    tinName: "Código Único de Identificación Tributaria",
    officialLanguageCode: "es",
    officialLanguageNameEn: "Spanish, Castilian",
    officialLanguageNameLocal: "Español",
    countryCallingCode: "54",
    region: "South/Latin America",
    flag: "🇦🇷"
  },
  {
    countryNameEn: "American Samoa",
    countryNameLocal: "American Samoa",
    countryCode: "AS",
    currencyCode: "USD",
    currencyNameEn: "United States dollar",
    tinType: "",
    tinName: "",
    officialLanguageCode: "en",
    officialLanguageNameEn: "English",
    officialLanguageNameLocal: "English",
    countryCallingCode: "1684",
    region: "Asia & Pacific",
    flag: "🇦🇸"
  }
];
