/* Generated by './build/bin/build-example.js' */

import ExampleBadgeDefault from './lib/badge/examples/example-badge-default';
import ExampleBadgeRound from './lib/badge/examples/example-badge-round';

const components = [
  ExampleBadgeDefault,
  ExampleBadgeRound
];

const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  ExampleBadgeDefault,
  ExampleBadgeRound
};
