/* Generated by './tools/bin/build-lib.js' */

import Accordion from '../src/lib/accordion/index.js';
import AccordionContent from '../src/lib/accordion/accordion-content/index.js';
import AccordionGroup from '../src/lib/accordion/accordion-group/index.js';
import AccordionHeader from '../src/lib/accordion/accordion-header/index.js';
import Alert from '../src/lib/alert/index.js';
import AlertBanner from '../src/lib/alert-banner/index.js';
import AlertContainer from '../src/lib/alert-container/index.js';
import AriaModal from '../src/lib/aria-modal/index.js';
import Avatar from '../src/lib/avatar/index.js';
import Badge from '../src/lib/badge/index.js';
import Breadcrumbs from '../src/lib/breadcrumbs/index.js';
import Button from '../src/lib/button/index.js';
import ButtonGroup from '../src/lib/button-group/index.js';
import Card from '../src/lib/card/index.js';
import CardSection from '../src/lib/card-section/index.js';
import Checkbox from '../src/lib/checkbox/index.js';
import CheckboxGroup from '../src/lib/checkbox-group/index.js';
import CloseIcon from '../src/lib/close-icon/index.js';
import CollapseButton from '../src/lib/collapse-button/index.js';
import ComboBox from '../src/lib/combo-box/index.js';
import CompositeAvatar from '../src/lib/composite-avatar/index.js';
import DataTable from '../src/lib/data-table/index.js';
import DataTableCheckbox from '../src/lib/data-table/data-table-checkbox/index.js';
import DataTableHeaderCheckbox from '../src/lib/data-table/data-table-header-checkbox/index.js';
import DataTableScrollView from '../src/lib/data-table/data-table-scroll-view/index.js';
import DataTableSortIcon from '../src/lib/data-table/data-table-sort-icon/index.js';
import DatePicker from '../src/lib/date-picker/index.js';
import DatePickerCalendar from '../src/lib/date-picker/date-picker-calendar/index.js';
import DatePickerDay from '../src/lib/date-picker/date-picker-day/index.js';
import DatePickerMonth from '../src/lib/date-picker/date-picker-month/index.js';
import DatePickerWeek from '../src/lib/date-picker/date-picker-week/index.js';
import EventOverlay from '../src/lib/event-overlay/index.js';
import FocusTrap from '../src/lib/focus-trap/index.js';
import Icon from '../src/lib/icon/index.js';
import Input from '../src/lib/input/index.js';
import InputHelper from '../src/lib/input-helper/index.js';
import InputMessage from '../src/lib/input-message/index.js';
import InputSearch from '../src/lib/input-search/index.js';
import InputSection from '../src/lib/input-section/index.js';
import Label from '../src/lib/label/index.js';
import Link from '../src/lib/link/index.js';
import List from '../src/lib/list/index.js';
import ListItem from '../src/lib/list-item/index.js';
import ListItemHeader from '../src/lib/list-item-header/index.js';
import ListItemSection from '../src/lib/list-item-section/index.js';
import ListSeparator from '../src/lib/list-separator/index.js';
import Loading from '../src/lib/loading/index.js';
import Modal from '../src/lib/modal/index.js';
import ModalBody from '../src/lib/modal-body/index.js';
import ModalFooter from '../src/lib/modal-footer/index.js';
import ModalHeader from '../src/lib/modal-header/index.js';
import Popover from '../src/lib/popover/index.js';
import Radio from '../src/lib/radio/index.js';
import RadioGroup from '../src/lib/radio-group/index.js';
import Select from '../src/lib/select/index.js';
import SelectOption from '../src/lib/select-option/index.js';
import Sidebar from '../src/lib/sidebar/index.js';
import SidebarBody from '../src/lib/sidebar/sidebar-body/index.js';
import SidebarFooter from '../src/lib/sidebar/sidebar-footer/index.js';
import SidebarHeader from '../src/lib/sidebar/sidebar-header/index.js';
import SidebarNav from '../src/lib/sidebar/sidebar-nav/index.js';
import SidebarNavItem from '../src/lib/sidebar/sidebar-nav-item/index.js';
import Slider from '../src/lib/slider/index.js';
import SliderPointer from '../src/lib/slider-pointer/index.js';
import Spinner from '../src/lib/spinner/index.js';
import Tab from '../src/lib/tabs/tab/index.js';
import TabContent from '../src/lib/tabs/tab-content/index.js';
import TabList from '../src/lib/tabs/tab-list/index.js';
import TabPane from '../src/lib/tabs/tab-pane/index.js';
import Tabs from '../src/lib/tabs/index.js';
import TimePicker from '../src/lib/time-picker/index.js';
import TimePickerDropdown from '../src/lib/time-picker/time-picker-dropdown/index.js';
import TimeSelector from '../src/lib/time-picker/time-selector/index.js';
import ToggleSwitch from '../src/lib/toggle-switch/index.js';
import Tooltip from '../src/lib/tooltip/index.js';
import Topbar from '../src/lib/topbar/index.js';
import TopbarMobile from '../src/lib/topbar/topbar-mobile/index.js';
import TopbarNav from '../src/lib/topbar/topbar-nav/index.js';
import TopbarRight from '../src/lib/topbar/topbar-right/index.js';

const components = [
  Accordion,
  AccordionContent,
  AccordionGroup,
  AccordionHeader,
  Alert,
  AlertBanner,
  AlertContainer,
  AriaModal,
  Avatar,
  Badge,
  Breadcrumbs,
  Button,
  ButtonGroup,
  Card,
  CardSection,
  Checkbox,
  CheckboxGroup,
  CloseIcon,
  CollapseButton,
  ComboBox,
  CompositeAvatar,
  DataTable,
  DataTableCheckbox,
  DataTableHeaderCheckbox,
  DataTableScrollView,
  DataTableSortIcon,
  DatePicker,
  DatePickerCalendar,
  DatePickerDay,
  DatePickerMonth,
  DatePickerWeek,
  EventOverlay,
  FocusTrap,
  Icon,
  Input,
  InputHelper,
  InputMessage,
  InputSearch,
  InputSection,
  Label,
  Link,
  List,
  ListItem,
  ListItemHeader,
  ListItemSection,
  ListSeparator,
  Loading,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Popover,
  Radio,
  RadioGroup,
  Select,
  SelectOption,
  Sidebar,
  SidebarBody,
  SidebarFooter,
  SidebarHeader,
  SidebarNav,
  SidebarNavItem,
  Slider,
  SliderPointer,
  Spinner,
  Tab,
  TabContent,
  TabList,
  TabPane,
  Tabs,
  TimePicker,
  TimePickerDropdown,
  TimeSelector,
  ToggleSwitch,
  Tooltip,
  Topbar,
  TopbarMobile,
  TopbarNav,
  TopbarRight
];

const install = Vue => {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  Accordion,
  AccordionContent,
  AccordionGroup,
  AccordionHeader,
  Alert,
  AlertBanner,
  AlertContainer,
  AriaModal,
  Avatar,
  Badge,
  Breadcrumbs,
  Button,
  ButtonGroup,
  Card,
  CardSection,
  Checkbox,
  CheckboxGroup,
  CloseIcon,
  CollapseButton,
  ComboBox,
  CompositeAvatar,
  DataTable,
  DataTableCheckbox,
  DataTableHeaderCheckbox,
  DataTableScrollView,
  DataTableSortIcon,
  DatePicker,
  DatePickerCalendar,
  DatePickerDay,
  DatePickerMonth,
  DatePickerWeek,
  EventOverlay,
  FocusTrap,
  Icon,
  Input,
  InputHelper,
  InputMessage,
  InputSearch,
  InputSection,
  Label,
  Link,
  List,
  ListItem,
  ListItemHeader,
  ListItemSection,
  ListSeparator,
  Loading,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Popover,
  Radio,
  RadioGroup,
  Select,
  SelectOption,
  Sidebar,
  SidebarBody,
  SidebarFooter,
  SidebarHeader,
  SidebarNav,
  SidebarNavItem,
  Slider,
  SliderPointer,
  Spinner,
  Tab,
  TabContent,
  TabList,
  TabPane,
  Tabs,
  TimePicker,
  TimePickerDropdown,
  TimeSelector,
  ToggleSwitch,
  Tooltip,
  Topbar,
  TopbarMobile,
  TopbarNav,
  TopbarRight
};
