/* Generated by './build/bin/build-lib.js' */

import Badge from '../src/lib/badge/index.vue';

const components = [
  Badge
];

const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  Badge
};
