/* Generated by './tools/bin/build-lib.js' */

import Alert from '../src/lib/alert/index.js';
import AlertBanner from '../src/lib/alert-banner/index.js';
import AlertContainer from '../src/lib/alert-container/index.js';
import AriaModal from '../src/lib/aria-modal/index.js';
import Badge from '../src/lib/badge/index.js';
import Breadcrumbs from '../src/lib/breadcrumbs/index.js';
import Button from '../src/lib/button/index.js';
import ButtonGroup from '../src/lib/button-group/index.js';
import Checkbox from '../src/lib/checkbox/index.js';
import CheckboxGroup from '../src/lib/checkbox-group/index.js';
import CloseIcon from '../src/lib/close-icon/index.js';
import EventOverlay from '../src/lib/event-overlay/index.js';
import FocusTrap from '../src/lib/focus-trap/index.js';
import Icon from '../src/lib/icon/index.js';
import Label from '../src/lib/label/index.js';
import List from '../src/lib/list/index.js';
import ListItem from '../src/lib/list-item/index.js';
import ListItemHeader from '../src/lib/list-item-header/index.js';
import ListItemSection from '../src/lib/list-item-section/index.js';
import ListSeparator from '../src/lib/list-separator/index.js';
import Loading from '../src/lib/loading/index.js';
import Modal from '../src/lib/modal/index.js';
import ModalBody from '../src/lib/modal-body/index.js';
import ModalFooter from '../src/lib/modal-footer/index.js';
import ModalHeader from '../src/lib/modal-header/index.js';
import Popover from '../src/lib/popover/index.js';
import Radio from '../src/lib/radio/index.js';
import RadioGroup from '../src/lib/radio-group/index.js';

const components = [
  Alert,
  AlertBanner,
  AlertContainer,
  AriaModal,
  Badge,
  Breadcrumbs,
  Button,
  ButtonGroup,
  Checkbox,
  CheckboxGroup,
  CloseIcon,
  EventOverlay,
  FocusTrap,
  Icon,
  Label,
  List,
  ListItem,
  ListItemHeader,
  ListItemSection,
  ListSeparator,
  Loading,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Popover,
  Radio,
  RadioGroup
];

const install = Vue => {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  Alert,
  AlertBanner,
  AlertContainer,
  AriaModal,
  Badge,
  Breadcrumbs,
  Button,
  ButtonGroup,
  Checkbox,
  CheckboxGroup,
  CloseIcon,
  EventOverlay,
  FocusTrap,
  Icon,
  Label,
  List,
  ListItem,
  ListItemHeader,
  ListItemSection,
  ListSeparator,
  Loading,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Popover,
  Radio,
  RadioGroup
};
