export interface ICountryCode {
  name: string;
  code: string;
  number: string;
}

export const CountryList: Array<ICountryCode> = [
  { name: 'Afghanistan', code: 'af', number: '93' },
  { name: 'Albania', code: 'al', number: '355' },
  { name: 'Algeria', code: 'dz', number: '213' },
  { name: 'American Samoa', code: 'as', number: '1684' },
  { name: 'Andorra', code: 'ad', number: '376' },
  { name: 'Angola', code: 'ao', number: '244' },
  { name: 'Anguilla', code: 'ai', number: '1264' },
  { name: 'Antigua and Barbuda', code: 'ag', number: '1268' },
  { name: 'Argentina', code: 'ar', number: '54' },
  { name: 'Armenia', code: 'am', number: '374' },
  { name: 'Aruba', code: 'aw', number: '297' },
  { name: 'Australia', code: 'au', number: '61' },
  { name: 'Austria', code: 'at', number: '43' },
  { name: 'Azerbaijan', code: 'az', number: '994' },
  { name: 'Bahamas', code: 'bs', number: '1242' },
  { name: 'Bahrain', code: 'bh', number: '973' },
  { name: 'Bangladesh', code: 'bd', number: '880' },
  { name: 'Barbados', code: 'bb', number: '1246' },
  { name: 'Belarus', code: 'by', number: '375' },
  { name: 'Belgium', code: 'be', number: '32' },
  { name: 'Belize', code: 'bz', number: '501' },
  { name: 'Benin', code: 'bj', number: '229' },
  { name: 'Bermuda', code: 'bm', number: '1441' },
  { name: 'Bhutan', code: 'bt', number: '975' },
  { name: 'Bolivia', code: 'bo', number: '591' },
  { name: 'Bosnia and Herzegovina', code: 'ba', number: '387' },
  { name: 'Botswana', code: 'bw', number: '267' },
  { name: 'Brazil', code: 'br', number: '55' },
  { name: 'British Indian Ocean Territory', code: 'io', number: '246' },
  { name: 'British Virgin Islands', code: 'vg', number: '1284' },
  { name: 'Brunei', code: 'bn', number: '673' },
  { name: 'Bulgaria', code: 'bg', number: '359' },
  { name: 'Burkina Faso', code: 'bf', number: '226' },
  { name: 'Burundi', code: 'bi', number: '257' },
  { name: 'Cambodia', code: 'kh', number: '855' },
  { name: 'Cameroon', code: 'cm', number: '237' },
  { name: 'Canada', code: 'ca', number: '1' },
  { name: 'Cape Verde', code: 'cv', number: '238' },
  { name: 'Caribbean Netherlands', code: 'bq', number: '599' },
  { name: 'Cayman Islands', code: 'ky', number: '1345' },
  { name: 'Central African Republic', code: 'cf', number: '236' },
  { name: 'Chad', code: 'td', number: '235' },
  { name: 'Chile', code: 'cl', number: '56' },
  { name: 'China', code: 'cn', number: '86' },
  { name: 'Colombia', code: 'co', number: '57' },
  { name: 'Comoros', code: 'km', number: '269' },
  { name: 'Congo (DRC)', code: 'cd', number: '243' },
  { name: 'Congo (Republic)', code: 'cg', number: '242' },
  { name: 'Cook Islands', code: 'ck', number: '682' },
  { name: 'Costa Rica', code: 'cr', number: '506' },
  { name: 'Côte d’Ivoire', code: 'ci', number: '225' },
  { name: 'Croatia', code: 'hr', number: '385' },
  { name: 'Cuba', code: 'cu', number: '53' },
  { name: 'Curaçao', code: 'cw', number: '599' },
  { name: 'Cyprus', code: 'cy', number: '357' },
  { name: 'Czech Republic', code: 'cz', number: '420' },
  { name: 'Denmark', code: 'dk', number: '45' },
  { name: 'Djibouti', code: 'dj', number: '253' },
  { name: 'Dominica', code: 'dm', number: '1767' },
  { name: 'Dominican Republic', code: 'do', number: '1' },
  { name: 'Egypt', code: 'eg', number: '20' },
  { name: 'El Salvador', code: 'sv', number: '503' },
  { name: 'Equatorial Guinea', code: 'gq', number: '240' },
  { name: 'Eritrea', code: 'er', number: '291' },
  { name: 'Estonia', code: 'ee', number: '372' },
  { name: 'Ethiopia', code: 'et', number: '251' },
  { name: 'Falkland Islands', code: 'fk', number: '500' },
  { name: 'Faroe Islands', code: 'fo', number: '298' },
  { name: 'Fiji', code: 'fj', number: '679' },
  { name: 'Finland', code: 'fi', number: '358' },
  { name: 'France', code: 'fr', number: '33' },
  { name: 'French Guiana', code: 'gf', number: '594' },
  { name: 'French Polynesia', code: 'pf', number: '689' },
  { name: 'Gabon', code: 'ga', number: '241' },
  { name: 'Gambia', code: 'gm', number: '220' },
  { name: 'Georgia', code: 'ge', number: '995' },
  { name: 'Germany', code: 'de', number: '49' },
  { name: 'Ghana', code: 'gh', number: '233' },
  { name: 'Gibraltar', code: 'gi', number: '350' },
  { name: 'Greece', code: 'gr', number: '30' },
  { name: 'Greenland', code: 'gl', number: '299' },
  { name: 'Grenada', code: 'gd', number: '1473' },
  { name: 'Guadeloupe', code: 'gp', number: '590' },
  { name: 'Guam', code: 'gu', number: '1671' },
  { name: 'Guatemala', code: 'gt', number: '502' },
  { name: 'Guinea', code: 'gn', number: '224' },
  { name: 'Guinea-Bissau', code: 'gw', number: '245' },
  { name: 'Guyana', code: 'gy', number: '592' },
  { name: 'Haiti', code: 'ht', number: '509' },
  { name: 'Honduras', code: 'hn', number: '504' },
  { name: 'Hong Kong', code: 'hk', number: '852' },
  { name: 'Hungary', code: 'hu', number: '36' },
  { name: 'Iceland', code: 'is', number: '354' },
  { name: 'India', code: 'in', number: '91' },
  { name: 'Indonesia', code: 'id', number: '62' },
  { name: 'Iran', code: 'ir', number: '98' },
  { name: 'Iraq', code: 'iq', number: '964' },
  { name: 'Ireland', code: 'ie', number: '353' },
  { name: 'Israel', code: 'il', number: '972' },
  { name: 'Italy', code: 'it', number: '39' },
  { name: 'Jamaica', code: 'jm', number: '1876' },
  { name: 'Japan', code: 'jp', number: '81' },
  { name: 'Jordan', code: 'jo', number: '962' },
  { name: 'Kazakhstan', code: 'kz', number: '7' },
  { name: 'Kenya', code: 'ke', number: '254' },
  { name: 'Kiribati', code: 'ki', number: '686' },
  { name: 'Kuwait', code: 'kw', number: '965' },
  { name: 'Kyrgyzstan', code: 'kg', number: '996' },
  { name: 'Laos', code: 'la', number: '856' },
  { name: 'Latvia', code: 'lv', number: '371' },
  { name: 'Lebanon', code: 'lb', number: '961' },
  { name: 'Lesotho', code: 'ls', number: '266' },
  { name: 'Liberia', code: 'lr', number: '231' },
  { name: 'Libya', code: 'ly', number: '218' },
  { name: 'Liechtenstein', code: 'li', number: '423' },
  { name: 'Lithuania', code: 'lt', number: '370' },
  { name: 'Luxembourg', code: 'lu', number: '352' },
  { name: 'Macau', code: 'mo', number: '853' },
  { name: 'Macedonia', code: 'mk', number: '389' },
  { name: 'Madagascar', code: 'mg', number: '261' },
  { name: 'Malawi', code: 'mw', number: '265' },
  { name: 'Malaysia', code: 'my', number: '60' },
  { name: 'Maldives', code: 'mv', number: '960' },
  { name: 'Mali', code: 'ml', number: '223' },
  { name: 'Malta', code: 'mt', number: '356' },
  { name: 'Marshall Islands', code: 'mh', number: '692' },
  { name: 'Martinique', code: 'mq', number: '596' },
  { name: 'Mauritania', code: 'mr', number: '222' },
  { name: 'Mauritius', code: 'mu', number: '230' },
  { name: 'Mexico', code: 'mx', number: '52' },
  { name: 'Micronesia', code: 'fm', number: '691' },
  { name: 'Moldova', code: 'md', number: '373' },
  { name: 'Monaco', code: 'mc', number: '377' },
  { name: 'Mongolia', code: 'mn', number: '976' },
  { name: 'Montenegro', code: 'me', number: '382' },
  { name: 'Montserrat', code: 'ms', number: '1664' },
  { name: 'Morocco', code: 'ma', number: '212' },
  { name: 'Mozambique', code: 'mz', number: '258' },
  { name: 'Myanmar (Burma)', code: 'mm', number: '95' },
  { name: 'Namibia', code: 'na', number: '264' },
  { name: 'Nauru', code: 'nr', number: '674' },
  { name: 'Nepal', code: 'np', number: '977' },
  { name: 'Netherlands', code: 'nl', number: '31' },
  { name: 'New Caledonia', code: 'nc', number: '687' },
  { name: 'New Zealand', code: 'nz', number: '64' },
  { name: 'Nicaragua', code: 'ni', number: '505' },
  { name: 'Niger', code: 'ne', number: '227' },
  { name: 'Nigeria', code: 'ng', number: '234' },
  { name: 'Niue', code: 'nu', number: '683' },
  { name: 'Norfolk Island', code: 'nf', number: '672' },
  { name: 'North Korea', code: 'kp', number: '850' },
  { name: 'Northern Mariana Islands', code: 'mp', number: '1670' },
  { name: 'Norway', code: 'no', number: '47' },
  { name: 'Oman', code: 'om', number: '968' },
  { name: 'Pakistan', code: 'pk', number: '92' },
  { name: 'Palau', code: 'pw', number: '680' },
  { name: 'Palestine', code: 'ps', number: '970' },
  { name: 'Panama', code: 'pa', number: '507' },
  { name: 'Papua New Guinea', code: 'pg', number: '675' },
  { name: 'Paraguay', code: 'py', number: '595' },
  { name: 'Peru', code: 'pe', number: '51' },
  { name: 'Philippines', code: 'ph', number: '63' },
  { name: 'Poland', code: 'pl', number: '48' },
  { name: 'Portugal', code: 'pt', number: '351' },
  { name: 'Puerto Rico', code: 'pr', number: '1' },
  { name: 'Qatar', code: 'qa', number: '974' },
  { name: 'Réunion', code: 're', number: '262' },
  { name: 'Romania', code: 'ro', number: '40' },
  { name: 'Russia', code: 'ru', number: '7' },
  { name: 'Rwanda', code: 'rw', number: '250' },
  { name: 'Saint Barthélemy', code: 'bl', number: '590' },
  { name: 'Saint Helena', code: 'sh', number: '290' },
  { name: 'Saint Kitts and Nevis', code: 'kn', number: '1869' },
  { name: 'Saint Lucia', code: 'lc', number: '1758' },
  { name: 'Saint Martin', code: 'mf', number: '590' },
  { name: 'Saint Pierre and Miquelon', code: 'pm', number: '508' },
  { name: 'Saint Vincent and the Grenadines', code: 'vc', number: '1784' },
  { name: 'Samoa', code: 'ws', number: '685' },
  { name: 'San Marino', code: 'sm', number: '378' },
  { name: 'São Tomé and Príncipe ', code: 'st', number: '239' },
  { name: 'Saudi Arabia', code: 'sa', number: '966' },
  { name: 'Senegal', code: 'sn', number: '221' },
  { name: 'Serbia', code: 'rs', number: '381' },
  { name: 'Seychelles', code: 'sc', number: '248' },
  { name: 'Sierra Leone', code: 'sl', number: '232' },
  { name: 'Singapore', code: 'sg', number: '65' },
  { name: 'Sint Maarten', code: 'sx', number: '1721' },
  { name: 'Slovakia', code: 'sk', number: '421' },
  { name: 'Slovenia', code: 'si', number: '386' },
  { name: 'Solomon Islands', code: 'sb', number: '677' },
  { name: 'Somalia', code: 'so', number: '252' },
  { name: 'South Africa', code: 'za', number: '27' },
  { name: 'South Korea', code: 'kr', number: '82' },
  { name: 'South Sudan', code: 'ss', number: '211' },
  { name: 'Spain', code: 'es', number: '34' },
  { name: 'Sri Lanka', code: 'lk', number: '94' },
  { name: 'Sudan', code: 'sd', number: '249' },
  { name: 'Suriname', code: 'sr', number: '597' },
  { name: 'Swaziland', code: 'sz', number: '268' },
  { name: 'Sweden', code: 'se', number: '46' },
  { name: 'Switzerland', code: 'ch', number: '41' },
  { name: 'Syria', code: 'sy', number: '963' },
  { name: 'Taiwan', code: 'tw', number: '886' },
  { name: 'Tajikistan', code: 'tj', number: '992' },
  { name: 'Tanzania', code: 'tz', number: '255' },
  { name: 'Thailand', code: 'th', number: '66' },
  { name: 'Timor-Leste', code: 'tl', number: '670' },
  { name: 'Togo', code: 'tg', number: '228' },
  { name: 'Tokelau', code: 'tk', number: '690' },
  { name: 'Tonga', code: 'to', number: '676' },
  { name: 'Trinidad and Tobago', code: 'tt', number: '1868' },
  { name: 'Tunisia', code: 'tn', number: '216' },
  { name: 'Turkey', code: 'tr', number: '90' },
  { name: 'Turkmenistan', code: 'tm', number: '993' },
  { name: 'Turks and Caicos Islands', code: 'tc', number: '1649' },
  { name: 'Tuvalu', code: 'tv', number: '688' },
  { name: 'U.S. Virgin Islands', code: 'vi', number: '1340' },
  { name: 'Uganda', code: 'ug', number: '256' },
  { name: 'Ukraine', code: 'ua', number: '380' },
  { name: 'United Arab Emirates', code: 'ae', number: '971' },
  { name: 'United Kingdom', code: 'gb', number: '44' },
  { name: 'United States', code: 'us', number: '1' },
  { name: 'Uruguay', code: 'uy', number: '598' },
  { name: 'Uzbekistan', code: 'uz', number: '998' },
  { name: 'Vanuatu', code: 'vu', number: '678' },
  { name: 'Vatican City', code: 'va', number: '39' },
  { name: 'Venezuela', code: 've', number: '58' },
  { name: 'Vietnam', code: 'vn', number: '84' },
  { name: 'Wallis and Futuna', code: 'wf', number: '681' },
  { name: 'Yemen', code: 'ye', number: '967' },
  { name: 'Zambia', code: 'zm', number: '260' },
  { name: 'Zimbabwe', code: 'zw', number: '263' },
];
